apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: motd-route
spec:
  template:
    apiVersion: v1
    kind: Route
    metadata:
      name: motd
    spec:
      to:
        kind: Service
        name: motd-service
